dojot/iotagent-mosca

- .travis.yml
- Dockerfile
- travis/publish.sh
This:
- is connected to dojot/dojot#273
- is connected to dojot/dojot#267
- is connected to dojot/dojot#272
- is connected to dojot/dojot#208
> Adds missing travis defs

- index.js
- package-lock.json
This is connected to dojot/dojot#267
> Updates iotagent-nodejs dependency version

- config.js
- index.js
> Adds config parameters to mosca

- index.js
This is connected to dojot/dojot#310
> Improves handling of non-conformant values for device information fields

- index.js
- package-lock.json
This is connected to dojot/dojot#384
> Adds actuation handler

- index.js
This is connected to dojot/dojot#533.
> Adding support for device generated timestamp

- travis/publish.sh
This is connected to dojot/dojot#563
> Fixing travis publish.sh script

- index.js
Partial refactoring. Including the following changes:
- ClientId must match the pattern tenant/deviceId
- Device must publish to topic: tenant/deviceId/attrs
- Device must subscribe to topic: tenant/deviceId/config
- Client certificate must has subject CN equals to deviceId
- Device model is kept locally while device is connected
- Removed the attrs level of the messages sent to devices
- Different rules to send tenant and deviceId information. They can be in the ClientId, User or Topic.
- getDevice method is called for every MQTT message
- Device identity is not …
> Partial refactoring of iotagent-mosca.

- index.js
feature: This PR introduce the compatibility between connections with TLS and without TLS.
Connections without TLS don't send clientID, So this is not processed.
The user can configure if want to use TLS. Then, connections without TLS is processed and the Tenant and deviceID is captured by topic.
This …
> Compatibility

- index.js
- package-lock.json
- package.json
This PR updates a few dependencies to their latest version.
Also it adds a tiny web server to receive log level changes and (in the future) users will be able to install this IoT agent through npm (such as npm install -g @dojot/iotagent-mqtt)
This iotagent doesn't accept new log levels after it started.
Log levels can't be changed.
No.
* **Is there any issue related to this PR in other …
> Fine tuning for new dependencies (libraries)

- index.js
- package.json
Feature
Today, doesn't have a healthCheck endpoint to check a status from service.
This PR introduce a endpoint 'healthCheck' to check a status from service.
No.
This PR is connected to dojot/dojot#768.
> Health check

- package.json
Bug Fix
When a new tenant is created, the IoT agent is not notified.
With the newer version of the lib, the IoT agent receives new-tenant events.
No
This PR is connected to dojot/dojot#781
> change iotagent-nodejs lib

- index.js
Bug fix
There is no validation if a device exists.
Now, messages are sending forward only if the device exists.
No
dojot/dojot#813
> Fixed how the device is being identified by the iot-agent

- .travis.yml
- Dockerfile
- conf.py
- config.js
- entrypoint.sh
- package-lock.json
- [NA ] Tests for the changes have been added (for bug fixes / features)
- [NA] Docs have been added / updated (for bug fixes / features)
Feature.
The docker image is built using the single-stage mode.
The docker image is built using the multi-stage mode.
No.
No.
To multi-stage …
> Improved how the docker image is built

- index.js
- package-lock.json
- package.json
This PR updates the version for all dependencies (at least for dojot's libraries). Also, now the process terminates if messenger can't be initiated.
> Update versions, add kill switch

- package-lock.json
- package.json
This PR sets the dependency for dojot-module as be just "compatible with 0.0.1-beta".
Any update will need a change in package.json.
The latest compatible version is installed when running `npm install` (and removing package-lock.json)
No.
This is connected to dojot/dojot#888
> Relaxed lib version master

- config.js
- index.js
FEATURE: Initial support for ratelimits
Initial support for ratelimits using redis decr and my small amount of knowledge in javascript. I don't know really if this is the right way to make this but i tried to make something.
Check if login passes and send the message.
Resolve the problem that is ratelimits in messages sent by the clients only if it is enabled.
In theory just set …
> [FEATURE] Initial support for ratelimits

- config.js
- healthcheck.js
- index.js
- package-lock.json
- package.json
This PR adds health check for the following:
- CPU utilization
- Memory usage
- Kafka connection
- Redis connection
- Uptime
Just memory utilization is observed.
All the aforementioned attributes are now observed.
This is connected to dojot/dojot#997
> Adding more health checks

- docs/operation.rst
Docs update
Removes metadata's templates property from the kafka message
> Updates documentation

- .gitignore
- index.js
> Add service metrics with mock

- .jshintrc
- index.js
> fix promise: even the device does not exist the process continues

- config.js
- index.js
- package-lock.json
- package.json
This PR set logger level of debug using a variable from docker-compose.yml passed through config.js
dojot/dojot#1177
> Log conf env var

- config.js
- index.js
This PR adds an event to handler with reject Promises and changes the variable used to set level of log, transforming it into object to get the level attribute
dojot/dojot#1186
> Reject promise handler

- Dockerfile
update
it was added tini to 'manage pid' when running the container.
> feat: add tini

- index.js
> feat:Log refactoring

- entrypoint.sh
- src/config.js
- src/index.js
- src/mosca.js
bug fix
fixed a case sensitive environment variable
* **Is there any issue related to this PR in another repository?** (such as dojot/dojot)
dojot/dojot#1170
Any number greater than 0 is true, and the whole word true, even in uppercase or lowercase is true, everything else is false.
> fix: case sensitive for unsecured mode env variable

- src/mosca.js
fix promise: even the device does not exist the process continues
#56 
> fix: even the device does not exist the process continues

- Readme.md
- package.json
- src/config.js
- src/mosca.js
- tests/moscaSetup.js
- tests/unit-tests/mosca.test.js
> feat: timeout by idle and lifetime 

- src/mosca.js
> fix: timeout by idle and lifetime

- package-lock.json
- package.json
- src/config.js
- src/index.js
- src/iotagent.js
Set a custom config for Apache Kafka
Using the dojot-module-nodejs config
You can set a custom config for Apache kafka
No
Yes, is connected to dojot/dojot#1449
It depends on PR https://github.com/dojot/iotagent-nodejs/pull/42 to work, because it uses this library as a …
> custom kafka params

- index.js
dojot/dojot#1732
- Use "Hide whitespace changes" to check "Files changed"
- This fix already exist in 0.5 and dev
> fix: The CN inside certificate isn't checked

- Readme.md
Docs update
https://github.com/dojot/dojot/issues/1584
> [dev] Change timestamp text

- Readme.md
Docs update
https://github.com/dojot/dojot/issues/1584
> [v0.5.0] Change timestamp text

- package-lock.json
- package.json
> [v0.5.0] updated iotagent-nodejs lib

- package-lock.json
- package.json
> [v0.4.4] updated iotagent-nodejs lib

- LICENSE
- license-exceptions.json
- package-lock.json
- package.json
license and version change
license GPL-3
license Apache-2
dojot/dojot#1879
> license and version change

- Readme.md
> change badge license

- LICENSE
- Readme.md
- license-exceptions.json
- package-lock.json
- package.json
> [v0.5.2] Cherry-picking licenses from development

- LICENSE
- Readme.md
- license-exceptions.json
- package-lock.json
- package.json
Be careful, see if it is necessary to update the branch! **Most likely it is not to update.**
> Merge version v0.5.2 from branch release/v0.5.2 to branch master

- .gitignore
- package-lock.json
- package.json
> changes to work with keycloak 
